# Generated by Django 3.1.5 on 2021-02-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
