# Generated by Django 3.1.5 on 2021-02-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20210203_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Storage',
        ),
    ]
